### ISSUE TITLE
definition

### ISSUE THREAD

**Issue by pnrobinson** [TheJacksonLaboratory/hpo-toolkit#61]
It would be useful to be able to get PMIDs that go with term definitions. In the JSON file these are listed as
```
 {
      "id" : "http://purl.obolibrary.org/obo/HP_0000011",
      "lbl" : "Neurogenic bladder",
      "type" : "CLASS",
      "meta" : {
        "definition" : {
          "val" : "A type of bladder dysfunction caused by neurologic damage. Neurogenic bladder can be flaccid or spastic. Com
mon manifestatios of neurogenic bladder are overflow incontinence, frequency, urgency, urge incontinence, and retention.",
          "xrefs" : [ "https://orcid.org/0000-0002-0736-9199", "PMID:18095004", "PMID:22400020" ]
        },
(...)
```
There are different ways we could model this in HPOTK; I do not think it is necessary to make them explicitly part of the definition, but they could be or each term could get a list of PMID_xref or something like that?

**Comment by ielis** [comment]
@pnrobinson pls review the PR #63 and give it a thumbs up if it looks OK.
