### ISSUE TITLE
loading hpo

### ISSUE THREAD

**Issue by pnrobinson** [TheJacksonLaboratory/hpo-toolkit#7]
It would be nice to have a convenience function for loading the hpo that would look if the HPO is already downloaded and if not pull in the latest version from GitHub, i.e., internally it would do somethinglike this
```
if os.path.isfile('hpo_data/hp.json'):
    hpo_ontology = load_ontology('hpo_data/hp.json')
else:
    hpo_ontology = load_ontology('https://raw.githubusercontent.com/obophenotype/human-phenotype-ontology/master/hp.json')
```

and client code would look like this
```
load_ontology()
# or if you want to make sure you have the latest version
load_ontology(overwrite=True)
```

**Comment by ielis** [comment]
Hi @pnrobinson thanks for a suggestion. It seems like this function should live above the more basic API that is already present in the library. I'll implement the convenience function in the next iteration.
